Remove unnecessary workflows and not use container for now

diff --git a/.github/workflows/linux-build-base.yml b/.github/workflows/linux-build-base.yml
--- a/.github/workflows/linux-build-base.yml
+++ b/.github/workflows/linux-build-base.yml
@@ -28,100 +28,6 @@ concurrency:
   cancel-in-progress: "${{github.ref != 'refs/heads/presto-0.293-clp-connector'}}"
 
 jobs:
-  adapters:
-    name: Linux release with adapters
-    runs-on: 8-core-ubuntu-22.04
-    container: ghcr.io/y-scope/clp/velox-dev:adapters
-    defaults:
-      run:
-        shell: bash
-    env:
-      CCACHE_DIR: "${{ github.workspace }}/ccache"
-      VELOX_DEPENDENCY_SOURCE: SYSTEM
-      GTest_SOURCE: BUNDLED
-      cudf_SOURCE: BUNDLED
-      CUDA_VERSION: "12.8"
-      USE_CLANG: "${{ inputs.use-clang && 'true' || 'false' }}"
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Fix git permissions
-        # Usually actions/checkout does this but as we run in a container
-        # it doesn't work
-        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
-
-      - name: Install Dependencies
-        run: |
-          # Allows to install arbitrary cuda-version whithout needing to update
-          # docker container before. It simplifies testing new/different versions
-          if ! yum list installed cuda-nvcc-$(echo ${CUDA_VERSION} | tr '.' '-') 1>/dev/null; then
-            source scripts/setup-centos9.sh
-            install_cuda ${CUDA_VERSION}
-          fi
-
-      - name: Install Minio
-        run: |
-          MINIO_BINARY="minio-2022-05-26"
-          if [ ! -f /usr/local/bin/${MINIO_BINARY} ]; then
-            wget https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2022-05-26T05-48-41Z -O ${MINIO_BINARY}
-            chmod +x ./${MINIO_BINARY}
-            mv ./${MINIO_BINARY} /usr/local/bin/
-          fi
-
-      - uses: assignUser/stash/restore@v1
-        with:
-          path: '${{ env.CCACHE_DIR }}'
-          key: ccache-linux-adapters-${{ inputs.use-clang && 'clang' || 'gcc' }}
-
-      - name: "Zero Ccache Statistics"
-        run: |
-          ccache -sz
-
-      - name: Make Release Build
-        env:
-          MAKEFLAGS: 'NUM_THREADS=8 MAX_HIGH_MEM_JOBS=4 MAX_LINK_JOBS=4'
-          CUDA_ARCHITECTURES: 70
-          CUDA_COMPILER: /usr/local/cuda-${CUDA_VERSION}/bin/nvcc
-          # Set compiler to GCC 12
-          CUDA_FLAGS: "-ccbin /opt/rh/gcc-toolset-12/root/usr/bin"
-        run: |
-          EXTRA_CMAKE_FLAGS=(
-            "-DVELOX_ENABLE_BENCHMARKS=ON"
-            "-DVELOX_ENABLE_EXAMPLES=ON"
-            "-DVELOX_ENABLE_ARROW=ON"
-            "-DVELOX_ENABLE_GEO=ON"
-            "-DVELOX_ENABLE_PARQUET=ON"
-            "-DVELOX_ENABLE_HDFS=ON"
-            "-DVELOX_ENABLE_S3=ON"
-            "-DVELOX_ENABLE_GCS=ON"
-            "-DVELOX_ENABLE_ABFS=ON"
-            "-DVELOX_ENABLE_REMOTE_FUNCTIONS=ON"
-            "-DVELOX_ENABLE_CUDF=ON"
-            "-DVELOX_ENABLE_WAVE=ON"
-            "-DVELOX_MONO_LIBRARY=ON"
-            "-DVELOX_BUILD_SHARED=ON"
-          )
-          if [[ "${USE_CLANG}" = "true" ]]; then scripts/setup-centos9.sh install_clang15; export CC=/usr/bin/clang-15; export CXX=/usr/bin/clang++-15; CUDA_FLAGS="-ccbin /usr/lib64/llvm15/bin/clang++-15"; fi
-          make release EXTRA_CMAKE_FLAGS="${EXTRA_CMAKE_FLAGS[*]}"
-
-      - name: Ccache after
-        run: ccache -s
-
-      - uses: assignUser/stash/save@v1
-        with:
-          path: '${{ env.CCACHE_DIR }}'
-          key: ccache-linux-adapters-${{ inputs.use-clang && 'clang' || 'gcc' }}
-
-      - name: Run Tests
-        # Some of the adapters dependencies are in the 'adapters' conda env
-        shell: mamba run --no-capture-output -n adapters /usr/bin/bash -e {0}
-        env:
-          LIBHDFS3_CONF: "${{ github.workspace }}/scripts/hdfs-client.xml"
-        working-directory: _build/release
-        run: |
-          export CLASSPATH=`/usr/local/hadoop/bin/hdfs classpath --glob`
-          ctest -j 8 --label-exclude cuda_driver --output-on-failure --no-tests=error
-
   ubuntu-debug:
     runs-on: 8-core-ubuntu-22.04
     name: "Ubuntu debug with resolve_dependency"
@@ -149,13 +55,66 @@ jobs:
         with:
           path: velox
 
-      - name: Install Dependencies
+      - name: Install Core Dependencies
         run: |
           source scripts/setup-ubuntu.sh && install_apt_deps
+
+      - name: Install Docs Dependencies
+        run: |
+          dnf install -y --setopt=install_weak_deps=False pandoc
+          pip3 install pipx
+          pipx install --force uv cmake==3.31
+          echo "PATH=$PATH:/github/home/.local/bin" >> $GITHUB_ENV
+          which uv
+          make python-venv
+          which uv
+          uv pip install -r scripts/docs-requirements.txt 
 
       - name: Clear CCache Statistics
         run: |
           ccache -sz
+
+      - name: Check Headers
+        run: |
+          make header-fix
+
+          if ! git diff --quiet; then
+            diff=`git --no-pager diff`
+            echo "Found missing License Header(s) in the following files:"
+            git --no-pager diff --name-only
+            echo "Check the Job summary for a copy-pasteable patch."
+
+            echo "> [!IMPORTANT]" >> $GITHUB_STEP_SUMMARY
+            echo "Found missing License Header(s)" >> $GITHUB_STEP_SUMMARY
+            echo "> Please apply fix using:"  >> $GITHUB_STEP_SUMMARY
+            echo "\`\`\`sh" >> $GITHUB_STEP_SUMMARY
+            echo "patch -p1 <<EOF" >> $GITHUB_STEP_SUMMARY
+            echo "$diff" >> $GITHUB_STEP_SUMMARY
+            echo "EOF" >> $GITHUB_STEP_SUMMARY
+            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+
+      - name: Check Format
+        run: |
+          make format-fix
+
+          if ! git diff --quiet; then
+            diff=`git --no-pager diff`
+            echo "Found format issues in the following files:"
+            git --no-pager diff --name-only
+            echo "Check the Job summary for a copy-pasteable patch."
+
+            echo "> [!IMPORTANT]" >> $GITHUB_STEP_SUMMARY
+            echo "Found format issues" >> $GITHUB_STEP_SUMMARY
+            echo "> Please apply fix using:"  >> $GITHUB_STEP_SUMMARY
+            echo "\`\`\`sh" >> $GITHUB_STEP_SUMMARY
+            echo "patch -p1 <<EOF" >> $GITHUB_STEP_SUMMARY
+            echo "$diff" >> $GITHUB_STEP_SUMMARY
+            echo "EOF" >> $GITHUB_STEP_SUMMARY
+            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
 
       - name: Make Debug Build
         env:
@@ -166,6 +125,13 @@ jobs:
         run: |
           if [[ "${USE_CLANG}" = "true" ]]; then export CC=/usr/bin/clang-15; export CXX=/usr/bin/clang++-15; fi
           make debug
+
+      - name: Build Docs
+        run: |
+          source .venv/bin/activate
+          cd velox/docs
+          make clean
+          make html
 
       - name: CCache after
         run: |
